name: Terraform CI

on:
  pull_request:
    paths:
      - "environments/dev/**"
      - ".github/workflows/terraform.yml"

  push:
    branches:
      - main
    paths:
      - "environments/dev/**"
      - ".github/workflows/terraform.yml"

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    name: Terraform Validate and Plan
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: environments/dev

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::042134552486:role/ObservabilityAsCodeGitHubActionsRole
          aws-region: ap-south-1

      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      - name: Terraform Init
        run: terraform init -input=false

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -input=false -out=tfplan

      - name: Upload Terraform Plan
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan
          path: environments/dev/tfplan

  terraform-apply:
    name: Terraform Apply
    needs: terraform
    runs-on: ubuntu-latest

    environment:
      name: production

    permissions:
      id-token: write
      contents: read

    defaults:
      run:
        working-directory: environments/dev

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Download Terraform Plan
        uses: actions/download-artifact@v4
        with:
          name: terraform-plan
          path: environments/dev

      - name: Debug Apply OIDC claims
        env:
          ACTIONS_ID_TOKEN_REQUEST_URL: ${{ env.ACTIONS_ID_TOKEN_REQUEST_URL }}
          ACTIONS_ID_TOKEN_REQUEST_TOKEN: ${{ env.ACTIONS_ID_TOKEN_REQUEST_TOKEN }}
        run: |
          TOKEN=$(curl -sS \
            -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
            "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=sts.amazonaws.com" | jq -r '.value')

          export PAYLOAD=$(echo "$TOKEN" | cut -d '.' -f 2)

          python3 -c '
          import base64, json, os
          token = os.environ["PAYLOAD"]
          token += "=" * (-len(token) % 4)
          claims = json.loads(base64.urlsafe_b64decode(token))

          for key in ["iss", "sub", "aud", "repository", "repository_id",
                      "repository_owner", "repository_owner_id",
                      "environment", "ref", "event_name"]:
              print(f"{key}: {claims.get(key)}")
          '


     # - name: Configure AWS credentials
     #  uses: aws-actions/configure-aws-credentials@v4
     #   with:
     #     role-to-assume: arn:aws:iam::042134552486:role/ObservabilityAsCodeGitHubActionsRole
      #    aws-region: ap-south-1

      - name: Terraform Init
        run: terraform init -input=false

      - name: Terraform Apply
        run: terraform apply -input=false tfplan
