name: Terraform CI

on:
  pull_request:
    paths:
      - "environments/dev/**"
      - ".github/workflows/terraform.yml"

  push:
    branches:
      - main
    paths:
      - "environments/dev/**"
      - ".github/workflows/terraform.yml"

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    name: Terraform Validate and Plan
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: environments/dev

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3


      - name: Debug GitHub OIDC context
        run: |
          echo "Repository: $GITHUB_REPOSITORY"
          echo "Ref: $GITHUB_REF"
          echo "Event: $GITHUB_EVENT_NAME"
          echo "Actor: $GITHUB_ACTOR"
            
      - name: Debug OIDC claims
        env:
          ACTIONS_ID_TOKEN_REQUEST_URL: ${{ env.ACTIONS_ID_TOKEN_REQUEST_URL }}
          ACTIONS_ID_TOKEN_REQUEST_TOKEN: ${{ env.ACTIONS_ID_TOKEN_REQUEST_TOKEN }}
        run: |
          TOKEN=$(curl -sS \
            -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
            "$ACTIONS_ID_TOKEN_REQUEST_URL" | jq -r '.value')

          export PAYLOAD=$(echo "$TOKEN" | cut -d '.' -f 2)

          python3 -c '
          import base64, json, os
          token = os.environ["PAYLOAD"]
          token += "=" * (-len(token) % 4)
          claims = json.loads(base64.urlsafe_b64decode(token))
          for key in ["iss", "sub", "aud", "repository", "ref", "event_name"]:
              print(f"{key}: {claims.get(key)}")
          '    

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::042134552486:role/ObservabilityAsCodeGitHubActionsRole
          aws-region: ap-south-1

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::042134552486:role/ObservabilityAsCodeGitHubActionsRole
          aws-region: ap-south-1

      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      - name: Terraform Init
        run: terraform init -input=false

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -input=false
